// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyCpm_vJGaFUzpQSsbYsDg6i3bzJxQ9PA',
    appId: '1:686906001116:web:0da6cad7c505967934d619',
    messagingSenderId: '686906001116',
    projectId: 'gr12-2c77d',
    authDomain: 'gr12-2c77d.firebaseapp.com',
    storageBucket: 'gr12-2c77d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOSWwVVpeArpEisxiCikbYFvBem3iTowQ',
    appId: '1:686906001116:android:462029053493190234d619',
    messagingSenderId: '686906001116',
    projectId: 'gr12-2c77d',
    storageBucket: 'gr12-2c77d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK6-BLzLJvwSYr1wEIJrGlrKT6T8SmQas',
    appId: '1:686906001116:ios:fbd30a7c69934c3c34d619',
    messagingSenderId: '686906001116',
    projectId: 'gr12-2c77d',
    storageBucket: 'gr12-2c77d.appspot.com',
    iosBundleId: 'com.example.flutterApplication11',
  );
}
